services:
  - docker

before_install:
  - docker pull moss/xelatex


script:
  - docker run -v `pwd`:/data moss/xelatex make
  - find . ! -name '*.pdf' -delete 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
